version: "3.8"

services:
  face-similarity-judgement-service:
    container_name: face-similarity-judgement-container

    image: uttechcenter/face-similarity-judgement:v1.2.0

    ports:
      - "${SERVER_PORT}:8501"

    command: streamlit run server.py

    restart: always
